# Generated by Django 3.0 on 2021-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='project_screenshot')),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
