# Generated by Django 3.1 on 2021-04-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_description',
            new_name='project_description',
        ),
    ]
