# Generated by Django 3.0 on 2021-05-02 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210430_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='project_images'),
            preserve_default=False,
        ),
    ]
